AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: nature-talk Lambda (Custom Skill) with Secrets/SSM at runtime

Parameters:
  ProjectName:
    Type: String
    Default: nature-talk
  EnvName:
    Type: String
    AllowedValues: [dev, prod]
    Default: prod
  FunctionName:
    Type: String
    Default: nature-talk-fn
  AlexaSkillId:
    Type: String
    Description: "amzn1.ask.skill.xxxx-xxxx-xxxx-xxxx"

Resources:
  SmartHomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: src/
      Runtime: python3.11           # ← あなたの環境でビルド成功したバージョン
      Handler: lambda_function.lambda_handler
      Architectures: [x86_64]
      AutoPublishAlias: live        # 安定運用のため固定エイリアス
      Policies:
        - AWSLambdaBasicExecutionRole
        # SSM / Secrets 取得の権限（最小化したい場合は ARN を絞ってください）
        - Statement:
            - Effect: Allow
              Action: ssm:GetParameter
              Resource: "*"
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: "*"
      Environment:
        Variables:
          APP_ENV: !Ref EnvName
          # 実行時に参照する“名前”（値はテンプレートに含めない）
          ANTHROPIC_API_KEY_PARAM: !Sub "/${ProjectName}/${EnvName}/anthropic_api_key"
          ANTHROPIC_SECRET_ID: !Sub "${ProjectName}/anthropic"
      Events:
        FromAlexa:
          Type: AlexaSkill
          Properties:
            SkillId: !Ref AlexaSkillId

  # 任意：ログ保持期間を固定したい場合
  FunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FunctionName}"
      RetentionInDays: 14

Outputs:
  FunctionArn:
    Value: !Ref SmartHomeFunction
    Description: Function logical ID (alias-managed)
  AliasArn:
    Value: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionName}:live"
    Description: Use this ARN in Alexa Endpoint (Default Region)
